name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      #  usando o npm install com --force para atualizar o lockfile na marra
      - name: Install dependencies
        run: npm install --force

      # Apenas UMA etapa de lint ativa
      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build